export const SET_WEATHER_INFO = "SET_WEATHER_INFO";
export const SET_QUERY_PARAMS = "SET_QUERY_PARAMS";
export const SET_LOADING = "SET_LOADING";
export const SET_WEATHER_WEEK_INFO = "SET_WEATHER_WEEK_INFO";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
